Repository Team-SSOK/ssok-backend, pull requests merged in 2025-04, with the labels that each got.

#7 feat : gateway, config 모듈 초기 세팅
  settings.gradle
  ssok-config/.gitattributes
  ssok-config/.gitignore
  ssok-config/build.gradle
  ssok-config/gradle/wrapper/gradle-wrapper.jar
  ssok-config/gradlew
  ssok-config/gradlew.bat
  ssok-config/src/main/java/kr/ssok/config/SsokConfigApplication.java
  ssok-config/src/test/java/kr/ssok/config/SsokConfigApplicationTests.java
  ssok-gateway/.gitattributes
  ssok-gateway/.gitignore
  ssok-gateway/build.gradle
  ssok-gateway/gradle/wrapper/gradle-wrapper.jar
  ssok-gateway/gradlew
  ssok-gateway/gradlew.bat
  ssok-gateway/src/main/java/kr/ssok/gateway/SsokGatewayApplication.java
  ssok-gateway/src/test/java/kr/ssok/gateway/SsokGatewayApplicationTests.java
  ssok-transfer-service/gradle/wrapper/gradle-wrapper.properties
  ssok-transfer-service/src/main/resources/application.yml
Labels: enhancement

#10 feat : common 모듈에 baseResponse, jackson 의존성추가 (#8, SCRUM-114)
  build.gradle
  settings.gradle
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountException.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountExceptionHandler.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-common/build.gradle
  ssok-common/src/main/java/kr/ssok/common/exception/BaseException.java
  ssok-common/src/main/java/kr/ssok/common/exception/BaseResponse.java
  ssok-common/src/main/java/kr/ssok/common/exception/CommonResponseStatus.java
  ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java
  ssok-common/src/main/java/kr/ssok/common/exception/ResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferException.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserException.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserExceptionHandler.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
Labels: enhancement

#12 feat/test: 송금 기능 개발 및 거래 내역 저장 및 테스트 코드 (#3 #13, SCRUM-52)
  build.gradle
  settings.gradle
  ssok-common/src/main/java/kr/ssok/common/util/TestUtil.java
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/SsokTransferServiceApplication.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/OpenBankingTransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/TransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/Transfer.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/TransferHistory.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/enums/CurrencyCode.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/enums/TransferMethod.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/enums/TransferType.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferHistoryRepository.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferRepository.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/SsokTransferServiceApplicationTestsHistory.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement

#26 feat: 연동 계좌 삭제 기능 구현 & 테스트 (#23, SCRUM-59)
  ssok-account-service/src/main/java/kr/ssok/accountservice/SsokAccountServiceApplication.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/entity/LinkedAccount.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountServiceImplTest.java
  ssok-common/src/main/java/kr/ssok/common/entity/TimeStamp.java
Labels: enhancement

#31 feat: pin 재설정, 인증요청 / 유저 정보 조회 (#30, SCRUM-121)
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PinCodeRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/UserInfoResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/ProfileImage.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/UserService.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#34 feat/test: 최신 송금자 내역 조회 기능 및 테스트 (#28, SCRUM-62)
  ssok-transfer-service/.gitignore
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/QueryDSLConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/TransferConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferHistoryController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferCounterpartResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferHistoryRepository.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/TransferHistoryRepositoryCustom.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/impl/TransferHistoryRepositoryImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferHistoryService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement, test

#36 feat: 약관 목록 조회, 약관 상세 조회 API (#32, SCRUM-118)
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/TermsController.java
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/TermsDetailResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/TermsListResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/Terms.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/repository/TermsRepository.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/TermsService.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/TermsServiceImpl.java
Labels: enhancement

#37 feat: 오픈뱅킹에 송금 요청 시, 입/출금 계좌의 예금주명 포함하도록 수정 (#35, SCRUM-127)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/OpenBankingTransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
Labels: enhancement

#38 feat: 주 계좌 변경 & 계좌 별명 수정 기능 구현 및 테스트 (#33, SCRUM-130)
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/request/UpdateAliasRequestDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/entity/LinkedAccount.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/repository/AccountRepository.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountServiceImplTest.java
Labels: enhancement

#41 test: user-service 계층 별 단위 테스트 (#40, SCRUM-123)
  ssok-user-service/build.gradle
  ssok-user-service/src/main/java/kr/ssok/userservice/config/JpaAuditingConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PhoneVerificationRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PinCodeRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/SignupRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/BankAccountResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
  ssok-user-service/src/test/java/kr/ssok/userservice/config/TestAuditConfig.java
  ssok-user-service/src/test/java/kr/ssok/userservice/config/TestSecurityConfig.java
  ssok-user-service/src/test/java/kr/ssok/userservice/controller/TermsControllerTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/controller/UserControllerTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/entity/ProfileImageTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/entity/TermsTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/entity/UserTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/repository/TermsRepositoryTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/repository/UserRepositoryTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/service/impl/TermsServiceImplTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/service/impl/UserServiceImplTest.java
Labels: test

#42 test : 통합 테스트 (#40, SCRUM-138)
  ssok-common/src/main/java/kr/ssok/common/exception/BaseResponse.java
  ssok-common/src/main/java/kr/ssok/common/exception/CommonResponseStatus.java
  ssok-notification-service/build.gradle
  ssok-user-service/src/main/java/kr/ssok/userservice/client/AligoClient.java
  ssok-user-service/src/main/java/kr/ssok/userservice/config/PasswordConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/repository/UserRepository.java
  ssok-user-service/src/test/java/kr/ssok/userservice/config/MockExternalSystemConfig.java
  ssok-user-service/src/test/java/kr/ssok/userservice/config/TestRedisConfig.java
  ssok-user-service/src/test/java/kr/ssok/userservice/integration/ExternalSystemIntegrationTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/integration/PinChangeIntegrationTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/integration/SignupIntegrationTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/integration/TermsIntegrationTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/integration/UserInfoIntegrationTest.java
  ssok-user-service/src/test/java/kr/ssok/userservice/util/TestUtils.java
Labels: test
