Repository Team-SSOK/ssok-backend, pull requests merged in 2025-06, with the labels that each got.

#197 feat: 송금 시, 알림 kafka fallback 처리 (#196, SCURM-244)
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/controller/FcmController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/enums/BankCode.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/helper/TransferNotificationSender.java
Labels: bug, enhancement

#226 feat: 휴대폰 인증 기반 회원가입 및 PIN 재등록 로직 개선
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/CompleteSignupRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/ReRegisterPinRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/PhoneVerificationResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/UserService.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#227 feat: 휴대폰 인증 기반 회원가입 및 PIN 재등록 로직 개선
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java
  ssok-user-service/src/main/java/kr/ssok/userservice/config/RedisConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
Labels: enhancement

#221 refactor: 내부 통신 REST -> gRPC 으로 리팩토링 (#157/SCRUM-143)
  ssok-account-service/build.gradle
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/AopConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/GrpcClientConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/GrpcServerConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/GrpcExceptionHandlingAspect.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/grpc/GrpcExceptionUtil.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/grpc/client/UserServiceClient.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/grpc/server/AccountGrpcInternalServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
  ssok-bluetooth-service/build.gradle
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/config/AopConfig.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/config/GrpcClientConfig.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/GrpcExceptionHandlingAspect.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/grpc/GrpcExceptionUtil.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/grpc/client/AccountServiceClient.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/grpc/client/UserServiceClient.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
  ssok-common/build.gradle
  ssok-common/src/main/proto/account_service.proto
  ssok-common/src/main/proto/user_service.proto
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/AopConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/GrpcClientConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/GrpcExceptionHandlingAspect.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/grpc/GrpcExceptionUtil.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/grpc/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/helper/AccountInfoResolver.java
  ssok-user-service/build.gradle
  ssok-user-service/src/main/java/kr/ssok/userservice/config/GrpcServerConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/grpc/GrpcExceptionUtil.java
  ssok-user-service/src/main/java/kr/ssok/userservice/grpc/server/UserGrpcInternalServiceImpl.java
Labels: enhancement

#232 hotfix : gateway grpc 의존성 누락
  ssok-gateway-service/build.gradle
Labels: bug

#234 hotfix : gateway grpc 의존성 충돌
  ssok-gateway-service/build.gradle
Labels: bug

#235 hotfix: gRPC 도입 후, transfer 서버 에러 수정
  ssok-transfer-service/build.gradle
Labels: bug

#237 fix: transfer service gradle 추가 수정
  ssok-transfer-service/build.gradle
Labels: bug

#244 fix : aligo testmode 제거
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/controller/AligoController.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/service/AligoService.java
Labels: enhancement

#246 hotfix: kafka fcm exception swallow 문제 해결(#243, SCRUM-281)
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/client/FirebaseClient.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/KafkaConsumerConfig.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/kafka/consumer/NotificationConsumer.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/kafka/handler/KafkaDltHandler.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationResponseStatus.java
Labels: bug

#252 fix: account service grpc method 수정 (#243, SCRUM-281)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/grpc/client/AccountService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/grpc/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: bug

#255 feat: 최신 송금자 조회시, 뱅크 코드 추가 (#254, SCRUM-287)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferCounterpartResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/TransferHistory.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/impl/TransferHistoryRepositoryImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/helper/TransferHistoryRecorder.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
Labels: enhancement

#259 refactor: 송금 서비스 오픈 뱅킹 요청 webclient 적용 (#222, SCRUM-280)
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/webclient/OpenBankingApiClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/webclient/impl/OpenBankingApiClientImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/AsyncConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/WebClientConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement
