Repository Team-SSOK/ssok-backend, pull requests merged in 2025-05, with the labels that each got.

#45 feat: 계좌 번호 조회 & 계좌 ID 조회 & 연동 계좌 전체 조회 (송금 서버 연동 부분) 구현 및 테스트 (#44, SCRUM-132)
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/openbanking/OpenBankingAllAccountsResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/AccountIdResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/AccountInfoResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/userservice/UserInfoResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/entity/LinkedAccount.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/repository/AccountRepository.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountInternalService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImplTest.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountServiceImplTest.java
Labels: enhancement

#52 feat/test: uuid 리스트로 user 정보 조회 및 사용자 주계좌 조회 (#50, SCRUM-126)
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/SsokBluetoothServiceApplication.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/UserServiceClient.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/AccountInfoDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/UserInfoDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/controller/BluetoothController.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/BluetoothMatchRequestDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/BluetoothMatchResponseDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/BluetoothService.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
  ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountIdResponse.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountIdsResponse.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountResponse.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/OpenBankingTransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement, test

#54 refactor: 예외처리 코드 수정 (#47, SCRUM-147)
  ssok-account-service/build.gradle
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/RedisConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/entity/LinkedAccount.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/repository/AccountRepository.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/util/AccountIdentifierUtil.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImplTest.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountServiceImplTest.java
Labels: enhancement

#57 feat/test/refactor: 블루투스 송금 기능 (#53, SCRUM-148)
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/AccountInfoDto.java
  ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/request/OpenBankingTransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdsResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/PrimaryAccountResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/BluetoothTransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/BluetoothTransferResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement, test

#60 feat: 오픈뱅킹 통신 에러처리 (#59, SCRUM-134)
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothExceptionHandler.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/OpenBankingResponse.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/FeignClientDecoderConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/TransferRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/feign/FeignClientGlobalErrorDecoder.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement

#66 fix: 유저 서비스 - 계좌 서비스 통신 URL 수정 (#65, SCRUM-156)
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/UserServiceClient.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java
Labels: bug

#67 feat: 블루투스, 송금 서비스 스웨거 추가 (#64, SCRUM-155)
  settings.gradle
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/config/SwaggerConfig.java
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/SwaggerConfig.java
Labels: enhancement

#68 hotfix: 계좌 - 송금 서비스 간의 URL 수정
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
Labels: bug

#72 Hotfix : msa 통합 테스트 중 수정사항 반영
  docker-compose.yml
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/SwaggerConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/config/SecurityConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/config/SwaggerConfig.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
  ssok-user-service/src/main/java/kr/ssok/userservice/repository/ProfileImageRepository.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#73 주 계좌 정보 조회 기능 (송금 서버 연동) 구현 (#69. SCRUM-159)
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/PrimaryAccountInfoResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountInternalService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImplTest.java
Labels: enhancement

#74 feat: spring cloud config -> spring cloud kubernetes / config refactor (#58/SCRUM-146)
  ssok-account-service/build.gradle
  ssok-bluetooth-service/build.gradle
  ssok-gateway/build.gradle
  ssok-notification-service/build.gradle
  ssok-transfer-service/build.gradle
  ssok-user-service/build.gradle
Labels: enhancement

#77 remove : 기존의 config service 제거
  settings.gradle
  ssok-config/.gitattributes
  ssok-config/.gitignore
  ssok-config/build.gradle
  ssok-config/gradle/wrapper/gradle-wrapper.jar
  ssok-config/gradlew
  ssok-config/gradlew.bat
  ssok-config/src/main/java/kr/ssok/config/SsokConfigApplication.java
  ssok-config/src/test/java/kr/ssok/config/SsokConfigApplicationTests.java
Labels: enhancement

#79 fix : jenkinsfile feature, 남아있던 config 관련 build 삭제
  Jenkinsfile
  build.gradle
Labels: enhancement

#81 test : jenkins build test
  .dockerignore
  Dockerfile
  Jenkinsfile
  README.md
  setup.sh
  ssok-account-service/Dockerfile
  ssok-bluetooth-service/Dockerfile
  ssok-gateway/Dockerfile
  ssok-gateway/build.gradle
  ssok-notification-service/Dockerfile
  ssok-transfer-service/Dockerfile
  ssok-user-service/Dockerfile
  ssok-user-service/build.gradle
Labels: test

#82 fix : jenkinsfile celanWs() 로 수정
  Jenkinsfile
Labels: test

#84 test : user-service ci test
  setup.sh
Labels: test

#85 test : gateway ci test
  ssok-gateway/build.gradle
Labels: test

#90 test : jenkins 빌드 common 모듈 선 빌드되도록
  Jenkinsfile
  ssok-common/build.gradle
Labels: test

#92 test : jenkins build test
  ssok-gateway/build.gradle
Labels: test

#94 test : jenkinsfile git pull 제거 build test
  Jenkinsfile
Labels: test

#97 test : jenkins ci 시작 시에 cleanWs() 추가3
  Jenkinsfile
Labels: test

#98 test : jenkins ci 끝나고 cleanWs() 추가4
  Jenkinsfile
Labels: test

#99 test : jenkins build test
  ssok-gateway/build.gradle
Labels: test

#102 test : 공용모듈 빌드 의존성 문제 해결 시도
  Jenkinsfile
  ssok-account-service/Dockerfile
  ssok-bluetooth-service/Dockerfile
  ssok-common/build.gradle
  ssok-common/src/main/java/kr/ssok/common/exception/CommonResponseStatus.java
  ssok-gateway/Dockerfile
  ssok-notification-service/Dockerfile
  ssok-transfer-service/Dockerfile
  ssok-user-service/Dockerfile
Labels: test

#104 test : target jar -> docker image build 방식으로 변경 - build test
  ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java
Labels: test

#105 test : argroCD 동작 test
  ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java
Labels: test

#106 feat: 푸시 알림 기능 (#75, SCRUM-161)
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
  ssok-notification-service/.gitignore
  ssok-notification-service/build.gradle
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/controller/AligoController.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/dto/AligoVerificationRequestDto.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/service/AligoService.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/client/FirebaseClient.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/FirebaseConfig.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/RedisConfig.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/SwaggerConfig.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/controller/FcmController.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/request/FcmMessageRequestDto.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/request/FcmRegisterRequestDto.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/FcmService.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/FcmServiceImpl.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/NotificationServiceImpl.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/NotificationService.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationException.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationExceptionHandler.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/TransferHistory.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement

#109 fix : jenkinsfile에 firebase sdk 추가
  Jenkinsfile
Labels: enhancement

#110 test : jenkins 전체 빌드 test
  ssok-common/build.gradle
Labels: test

#111 fix : jenkinsfile gateway -> gateway-service
  Jenkinsfile
Labels: test

#112 fix : jenkinsfile gateway -> gateway-service
  Jenkinsfile
Labels: test

#113 fix : ssok-gateway -> ssok-gateway-service
  settings.gradle
  ssok-gateway-service/.gitattributes
  ssok-gateway-service/.gitignore
  ssok-gateway-service/Dockerfile
  ssok-gateway-service/build.gradle
  ssok-gateway-service/gradle/wrapper/gradle-wrapper.jar
  ssok-gateway-service/gradlew
  ssok-gateway-service/gradlew.bat
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/SsokGatewayApplication.java
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/config/RedisConfig.java
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/config/SecurityConfig.java
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/security/filter/JwtAuthenticationFilter.java
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/security/handler/JwtAuthenticationEntryPoint.java
  ssok-gateway-service/src/main/java/kr/ssok/gatewayservice/security/jwt/JwtVerifier.java
  ssok-gateway-service/src/test/java/kr/ssok/gatewayservice/SsokGatewayApplicationTests.java
Labels: enhancement, test

#114 fix : ssok-gateway -> ssok-gateway-service
  Jenkinsfile
  build.gradle
  ssok-gateway-service/src/main/java/kr/ssok/gateway/SsokGatewayApplication.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/RedisConfig.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/handler/JwtAuthenticationEntryPoint.java
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/jwt/JwtVerifier.java
  ssok-gateway-service/src/test/java/kr/ssok/gateway/SsokGatewayApplicationTests.java
Labels: enhancement, test

#115 fix : kubernetes config, yml 변환 시 복수 value 파싱 문제로 whitelist 코드단에 직접 주입 방식으로 변경
  ssok-common/build.gradle
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
Labels: enhancement, test

#116 fix : kubernetes config, yml 변환 시 복수 value 파싱 문제로 whitelist 코드단에 직접 주입 방식으로 변경 (완전삭제)
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
Labels: enhancement, test

#117 fix : kubernetes config yml / JwtAuthenticationFilter 부분 추가 수정
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java
Labels: enhancement, test

#118 test : 전체 빌드 test
  ssok-common/build.gradle
Labels: test

#119 refactor: 오픈뱅킹 서버 API 요청에 대한 에러 응답 처리 (#107, SCRUM-153)
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/dto/response/OpenBankingResponse.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/FeignClientDecoderConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/JpaAuditingConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/config/SwaggerConfig.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/feign/FeignClientGlobalErrorDecoder.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java
Labels: enhancement

#61 refactor: gRPC 구현을 위한 gradle 설정 (#61, SCRUM-144)
  settings.gradle
  ssok-account-service/build.gradle
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
  ssok-bluetooth-service/build.gradle
  ssok-transfer-service/build.gradle
  ssok-user-service/build.gradle
Labels: enhancement

#120 fix : jakartaAnnotation 버전 up!
  settings.gradle
Labels: enhancement

#121 fix : 회원가입 api에 bank service랑 연동 주석 제거
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#124 fix : 연동api 뱅크서버 계좌생성에 userTypeCode 추가 (#123/SCRUM-168)
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/BankAccountRequestDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#125 refactor: 오픈뱅킹 요청 로직 헤더에 API 키 추가 (#122, SCRUM-167)
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
  ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: enhancement

#127 fix : aligoClient url 수정
  ssok-user-service/build.gradle
Labels: enhancement

#128 fix : 내부 클러스터 ip 수정 반영
  ssok-common/build.gradle
Labels: enhancement

#129 fix : test를 위한 전체 재배포
  ssok-common/build.gradle
Labels: enhancement

#130 refactor: 계좌 서버 외부 호출용 API URL 변경 (#126, SCRUM-170)
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountOpenBankingController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
Labels: enhancement

#131 feat: 송금 푸시 알림 kafka 적용 (#108, SCRUM-164)
  ssok-notification-service/build.gradle
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/KafkaConsumerConfig.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/controller/FcmController.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/message/KafkaNotificationMessageDto.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/request/FcmNotificationRequestDto.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/message/NotificationConsumer.java
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/NotificationServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/request/FcmNotificationRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdsResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/KafkaProducerConfig.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/kafka/message/KafkaNotificationMessageDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/kafka/producer/NotificationProducer.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: bug, enhancement

#133 fix: 블루투스 송금 푸시알림 kafka 적용 & 테스트 코드 수정 (#132, SCRUM-164)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: bug, enhancement

#138 fix: 오픈 뱅킹 송금 요청 api url 수정 (#134, SCRUM-172)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
Labels: bug

#140 fix : 회원가입시 전화번호 정규식 수정
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/SignupRequestDto.java
Labels: bug

#147 fix: 주 계좌 정보 조회 코드 오류 수정 (내부 서버 연동 API) (#146, SCRUM-180)
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
Labels: bug

#149 fix: 주 계좌 정보 조회 코드 오류 추가 수정 (내부 서버 연동 API) (#148, SCRUM-180)
  ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/bluetoothservice/PrimaryAccountBalanceResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/PrimaryAccountInfoResponseDto.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountInternalService.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
  ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java
Labels: bug

#150 fix: 블루투스 서비스 / 송금 서비스 수정
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/PrimaryAccountResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/feign/FeignClientGlobalErrorDecoder.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java
Labels: bug

#153 feat/test: 최근 송금 내역 조회 기능 & 테스트 코드 (#151#152, SCRUM-183)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferHistoryController.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferRecentHistoryResponseDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferHistoryRepository.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferHistoryService.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
  ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
Labels: enhancement, test

#156 fix: 블루투스 송금 내역 저장 문제 수정 (#154, SCRUM-184)
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/TransferBluetoothRequestDto.java
  ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
Labels: bug

#160 hotfix: redis fcm key 식별 에러 수정 & 푸시알림 body 수정(#159, SCRUM-190)
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/enums/BankCode.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/message/NotificationConsumer.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/FcmServiceImpl.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/NotificationServiceImpl.java
Labels: bug

#163 Feat : S3 기반 프로필 이미지 CRUD (#161 / scrum-122)
  ssok-user-service/build.gradle
  ssok-user-service/src/main/java/kr/ssok/userservice/config/S3Config.java
  ssok-user-service/src/main/java/kr/ssok/userservice/controller/ProfileController.java
  ssok-user-service/src/main/java/kr/ssok/userservice/dto/ProfileResponseDto.java
  ssok-user-service/src/main/java/kr/ssok/userservice/entity/ProfileImage.java
  ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
  ssok-user-service/src/main/java/kr/ssok/userservice/repository/ProfileImageRepository.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/ProfileService.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/S3FileService.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/ProfileServiceImpl.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/S3FileServiceImpl.java
Labels: enhancement

#164 Feat/#162/scrum 192
  settings.gradle
  ssok-account-service/build.gradle
  ssok-account-service/src/main/resources/logback-spring.xml
  ssok-bluetooth-service/build.gradle
  ssok-bluetooth-service/src/main/resources/logback-spring.xml
  ssok-gateway-service/build.gradle
  ssok-gateway-service/src/main/resources/logback-spring.xml
  ssok-notification-service/build.gradle
  ssok-notification-service/src/main/resources/logback-spring.xml
  ssok-transfer-service/build.gradle
  ssok-transfer-service/src/main/resources/logback-spring.xml
  ssok-user-service/build.gradle
  ssok-user-service/src/main/resources/logback-spring.xml
Labels: enhancement

#166 test : 전체 재 빌드
  ssok-common/build.gradle
Labels: bug

#169 test : 전체 재 빌드
  ssok-common/build.gradle
Labels: bug

#175 feat: prometheus 경로 추가 (#174, SCRUM-198)
  ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
Labels: enhancement

#176 feat: prometheus 경로 추가 (#174, SCRUM-198)
  ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java
Labels: enhancement

#178 test: opensearch alert test api 개발 (#177, SCRUM-214)
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/opensearch/controller/TestAlertController.java
Labels: test

#181 fix : S3 기본 파일(noImage) 관련 누락 수정
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/ProfileServiceImpl.java
  ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java
Labels: enhancement

#189 test: opensearch dashboard alert body 수정 (#187, SCRUM-238)
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/opensearch/controller/TestAlertController.java
  ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/opensearch/dto/LogDto.java
Labels: bug

#191 refactor/test: 블루투스 송금 로직 및 매칭 유저 정보 조회 리팩토링 & 테스트 코드 작성 (#158 #190, SCRUM-187)
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/TransferServiceClient.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/UserInfoDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/controller/TransferController.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/BluetoothTransferRequestDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/TransferRequestDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/BluetoothTransferResponseDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/UserInfoResponseDto.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/TransferService.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
  ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/TransferServiceImpl.java
  ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
  ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/TransferServiceImplTest.java
Labels: enhancement, test

#193 fix: 오픈뱅킹 잔액 조회 요청 기능 수정 (#192, SCRUM-240)
  ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
Labels: bug
